#ifndef CASEMATE_DUMMY_MACROS_H
#define CASEMATE_DUMMY_MACROS_H

#ifndef CONFIG_HAS_ASSERT
#define GHOST_LOG_CONTEXT_ENTER()
#define GHOST_LOG(NAME,TYPE)
#define GHOST_LOG_CONTEXT_EXIT()
#define GHOST_LOG_CONTEXT_ENTER_INNER(NAME)
#define GHOST_LOG_INNER(LOGNAME,NAME,TYPE)
#define GHOST_LOG_CONTEXT_EXIT_INNER(NAME)

#define GHOST_WARN(MSG) { \
		ghost_printf(GHOST_WHITE_ON_YELLOW "%s" GHOST_NORMAL "\n", MSG); \
	}
#endif

#endif /* CASEMATE_DUMMY_MACROS_H */