Casemate can be compiled as a standalone library, which can be linked into systems software, in order to:

* Generate `casemate-check`-compatible logs.

* Simulate the Casemate model and report violations at runtime.

[#casemate-model-init]
=== Compiling, linking, and the Ghost driver

Running `./configure` then `make` at the top-level should produce a `src/lib/casemate.o` object file and `src/lib/casemate.h` header.
These are what `casemate-check` use to drive the model, but can also be used by a third-party build process to link casemate into a pre-existing system.
Alternatively, one can build casemate directly in that toolchain, for example see `src/lib/Makefile.linux` for a Makefile which can be included from the Linux build system to include Casemate in the Linux kernel.

Configuring Casemate is relatively straightforward, with some premade configs. e.g. to build for FreeBSD (Kernel) run `./configure --config=FREEBSD_KERN` and then a simple `make` will produce FreeBSD compatible object files.

Once Casemate is available, the user needs call two initialisation functions:

* `initialise_ghost_driver` which provides Casemate a set of callbacks for performing side-effects in the system; and

* `initialise_casemate_model` passing some memory for Casemate to use to store the model state, and the initial model configuration options; often used in conjunction with `sizeof_casemate_model` to calculate the required size.

----
/* An example Casemate initialisation procedure */
struct casemate_options OPTS = CASEMATE_DEFAULT_OPTS;

void *initialise_casemate(void)
{
	int err;
	u64 size;
	void *st;
	struct casemate_options opts;

	struct ghost_driver sm_driver = {
		.putc = ...,
		.read_physmem = NULL,
		.read_sysreg = NULL,
		.abort = ...,
		.trace = ...,
	};
	initialise_ghost_driver(&sm_driver);

	size = sizeof_casemate_model(&OPTS);
	st = malloc(size);
	err = initialise_casemate_model(&OPTS, 0, 0, st, sm_size);
	assert(err == 0);
	return st;
}
----

[#casemate-model-cfg]
==== Casemate Model initialisation and configuration

An example configuration

----
(struct casemate_options){
  .enable_tracing = true,
  .enable_checking = true,
  .track_watchpoints = false,
  .log_opts = (struct casemate_log_options){
		.log_format_version = 1,
		.condensed_format = false,
	},
  .check_opts = (struct casemate_checker_options){
		.promote_DSB_nsh = false,
		.promote_TLBI_nsh = false,
		.promote_TLBI_by_id = false,
		.check_synchronisation = true,
		.enable_printing = false,
		.print_opts = CM_PRINT_DIFF_TO_STATE_ON_STEP | CM_PRINT_ONLY_UNCLEAN,
	},
  .enable_safety_checks = false,
}
----

****
See the full configuration datatype definition at https://github.com/rems-project/casemate/blob/main/src/lib/include/casemate-in/casemate-config.in.h.
****

The options should be passed to `initialise_casemate_model`, which takes a snapshot.
Options cannot currently be changed after initialisation.

===== Multi-instance loading

Casemate can be loaded multiple times and access the same underlying state.

To do this, the state must be initialised once with `initialise_casemate_model`,
which also initialises that instance;
*each instance* must have a driver initialised with `initialise_ghost_driver`;
then each non-initialised instance must be 'attached' to the initialised model state
with `attach_casemate_model`:

----
void load_second(void)
{
	/* already initialised MODEL in another component */
	initialise_ghost_driver(&driver);
	attach_casemate_model(MODEL);
}
----

[#casemate-model-driver]
==== Ghost driver

Whenever the Casemate model needs to perform an operation with or as a side-effect,
e.g. reading physical memory, printing a log record, or reporting a violation,
it does so through a generic _ghost driver_ that the user initialises as a struct-of-function-pointers.

An exmple driver from `casemate-check` is given below:

----
u64 __read_sysreg_cb(enum ghost_sysreg_kind sysreg)
{
	/* perform side-effect of reading system register */
}

void __abort_cb(const char *msg)
{
	exit(1);
}

/* outputs a single byte to 'stdout' */
void __putc_cb(char c)
{
	printf("%c", c);
}

/* logs a transition record */
void __trace_cb(const char *record)
{
	printf("%s\n", record);
}

/* casemate-check driver */
struct ghost_driver sm_driver = {
  .read_physmem = NULL,  /* casemate-check never reads real memory */
  .read_sysreg = __read_sysreg_cb,
  .abort = __abort_cb,
  .putc = __putc_cb,
  .trace = __trace_cb,
};
----

****
See the full `casemate-check` driver definition at https://github.com/rems-project/casemate/blob/main/src/casemate-check-c/src/driver.c.
****

=== Generating logs

Ensure `enable_tracing` is true in <<casemate-model-cfg,the configuration>>, and an appropriate `trace` callback is defined in <<casemate-model-driver,the driver>>,
then <<_stepping_the_model, stepping the model>> will output <<transitions,properly formatted trace records>>.

=== Configuring for runtime checks

Ensure `enable_checking` is true in <<casemate-model-cfg,the configuration>>, then <<_stepping_the_model>> will perform checks,
and report violations via the `abort` callback in <<casemate-model-driver,the driver>>.

=== Stepping the model

Once <<casemate-model-init,initialised>> the Casemate model is ready to begin taking steps immediately.

include::_lib_steps.adoc[]
