#!/usr/bin/env python
# Generates the top-level include/casemate.h

import pathlib
import argparse

HERE = pathlib.Path(__file__).parent
ROOT = HERE.parent

INCLUDE = ROOT / 'include'

compile_commands = []

template = (INCLUDE / "casemate-in" / "casemate.out.h").read_text()
helpers = (INCLUDE / "casemate-in" / "casemate-helpers.in.h").read_text()
ghost = (INCLUDE / "casemate-in" / "casemate-ghost-types.in.h").read_text()
state = (INCLUDE / "casemate-in" / "casemate-state.in.h").read_text()
transitions = (INCLUDE / "casemate-in" / "casemate-transitions.in.h").read_text()
config = (INCLUDE / "casemate-in" / "casemate-config.in.h").read_text()

def make_header(template):
  return (
    "/* autogenerated file, do not edit */\n" +
    (
      template
      .replace(
          "CASEMATE_STATE_H",
          state,
      ).replace(
          "CASEMATE_TRANSITIONS_H",
          transitions,
      ).replace(
          "CASEMATE_STEP_HELPERS_H",
          helpers
      ).replace(
          "CASEMATE_CONFIG_H",
          config
      ).replace(
          "CASEMATE_GHOST_H",
          ghost
      )
    )
  )

with open(INCLUDE / "casemate.h", "w") as f:
  f.write(make_header(template))
