name: CI

on:
  push:
    branches:
      - main
      - wip-github-ci
  pull_request:
    branches:
      - main

# cancel in-progress job when a new push is performed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: ubuntu-22.04

    timeout-minutes: 5
    steps:
    - run: mkdir -p rems-project

    - uses: actions/checkout@v3
      with:
        path: rems-project/casemate

    - name: System dependencies (ubuntu)
      run: |
        sudo apt update
        sudo apt install -y build-essential clang clang-format-15

    - name: Configure
      working-directory: rems-project/casemate
      run: |
        ./configure --clang-format=clang-format-15
        make dump-config

    - name: Build all
      working-directory: rems-project/casemate
      run: |
        make

    - name: clang-format
      working-directory: rems-project/casemate
      run: |
        make lint

    - name: Run tests
      working-directory: rems-project/casemate
      run: |
        make check-examples
